// @description wechat 是腾讯微信公众平台 api 的 golang 语言封装

package card

// 卡券类型
const (
	// 通用券
	CARD_TYPE_GENERAL_COUPON = "GENERAL_COUPON"
	// 团购券
	CARD_TYPE_GROUPON = "GROUPON"
	// 折扣券
	CARD_TYPE_DISCOUNT = "DISCOUNT"
	// 礼品券
	CARD_TYPE_GIFT = "GIFT"
	// 代金券
	CARD_TYPE_CASH = "CASH"
	// 会员卡
	CARD_TYPE_MEMBER_CARD = "MEMBER_CARD"
	// 门票
	CARD_TYPE_SCENIC_TICKET = "SCENIC_TICKET"
	// 电影票
	CARD_TYPE_MOVIE_TICKET = "MOVIE_TICKET"
	// 飞机票
	CARD_TYPE_BOARDING_PASS = "BOARDING_PASS"
	// 红包
	CARD_TYPE_LUCKY_MONEY = "LUCKY_MONEY"
)

//卡券code码展示类型
const (
	CODE_TYPE_TEXT    = "CODE_TYPE_TEXT"    // 文本
	CODE_TYPE_BARCODE = "CODE_TYPE_BARCODE" // 一维码（条形码）
	CODE_TYPE_QRCODE  = "CODE_TYPE_QRCODE"  // 二位啊
)

const (
	Date_Info_Type_Begin_End  = 1
	Date_Info_Type_Fixed_Term = 2
)

const (
	// 外卖
	URL_NAME_TYPE_TAKE_AWAY = "URL_NAME_TYPE_TAKE_AWAY"
	// 在线预订
	URL_NAME_TYPE_RESERVATION = "URL_NAME_TYPE_RESERVATION"
	// 立即使用
	URL_NAME_TYPE_USE_IMMEDIATELY = "URL_NAME_TYPE_USE_IMMEDIATELY"
	// 在线预约
	URL_NAME_TYPE_APPOINTMENT = "URL_NAME_TYPE_APPOINTMENT"
	//  在线兑换
	URL_NAME_TYPE_EXCHANGE = "URL_NAME_TYPE_EXCHANGE"
	URL_NAME_TYPE_MALL     = "URL_NAME_TYPE_MALL"
	// 车辆信息
	URL_NAME_TYPE_VEHICLE_INFORMATION = "URL_NAME_TYPE_VEHICLE_INFORMATION"
)
