package mass

const (
	MSG_WITH_GROUPID_TYPE_NEWS  = "mpnews"
	MSG_WITH_GROUPID_TYPE_TEXT  = "text"
	MSG_WITH_GROUPID_TYPE_VOICE = "voice"
	MSG_WITH_GROUPID_TYPE_IMAGE = "image"
	MSG_WITH_GROUPID_TYPE_VIDEO = "mpvideo"

	MSG_WITH_OPENIDLIST_TYPE_NEWS  = "mpnews"
	MSG_WITH_OPENIDLIST_TYPE_TEXT  = "text"
	MSG_WITH_OPENIDLIST_TYPE_VOICE = "voice"
	MSG_WITH_OPENIDLIST_TYPE_IMAGE = "image"
	MSG_WITH_OPENIDLIST_TYPE_VIDEO = "video"
)
